INFO 08-08 17:11:04 [__init__.py:244] Automatically detected platform cuda.
benchmarking facebook_opt-13b_prompt512_gen4096_bs1
Traceback (most recent call last):
  File "/home/ubuntu/vllm_eval/main.py", line 119, in <module>
    benchmark(args.model, args.prompt_len, args.gen_len, args.batch_size, args.tensor_parallelism)
  File "/home/ubuntu/vllm_eval/main.py", line 36, in benchmark
    modify_model_config(model_name, expected_model_len, tensor_parallelism)
  File "/home/ubuntu/vllm_eval/utils.py", line 121, in modify_model_config
    with open(_config_json, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/.cache/huggingface/models--facebook--opt-13b/blobs/d66132763e510905b39cbad4d7fd1b666a185e50'
